### ISSUE TITLE
Some documentation links provided by Configuration validation are invalid

### ISSUE THREAD

**Issue by mrand** [home-assistant/home-assistant.io#11184]
I'm putting this here because it seems like the documentation group would be in the best position to know the proper mapping and all the changes that were made and be able to use that to intelligently search and fix the links in the code.

If Configuration >> Server Control >> Check Config doesn't pass, some of the links it provides are invalid.   Here is an example:

> Invalid config for [device_tracker.netgear]: [url] is an invalid option for [device_tracker.netgear]. Check: device_tracker.netgear->url. (See ?, line ?). **Please check the docs at https://home-assistant.io/integrations/device_tracker.netgear/**

I remember noticing it on a few other even common yaml config items (which I didn't have time to document and have since forgotten), so I'm assuming there are a number of them that need to be looked for.

**Additional information:**

Supposedly bad config that generated the above is as follows:

```
device_tracker:
  - platform: netgear
    url: http://192.168.2.2
    username: admin
    password: !secret netgear_password
    port: 80
```

As a side thing, the config check appears to be saying the url: is not valid, but the documentation at https://www.home-assistant.io/integrations/netgear/ clearly shows it.
