### ISSUE TITLE
Resetup after Home Assistant restart

### ISSUE THREAD

**Issue by JoTec2002** [home-assistant/home-assistant.io#21282]
### Feedback

After each restart of Home Assistant the Doorbird no longer can trigger the events in Home Assistant.

It seams to me that the token in the URL gets invalid after a restart of Home Assistant.

Is there a workaround/ solution other than deleting and readding the Home Assistant Integration after each restart?

### URL

https://www.home-assistant.io/integrations/doorbird/

### Version

2021.12.10

**Comment by bdraco** [comment]
Please enable debug logs (https://www.home-assistant.io/integrations/logger/), restart, and post them.

Thanks 👍 

```
logger:
  default: info
  logs:
     requests: debug
     requests.packages.urllib3: debug
     urllib3.connectionpool: debug
     urllib3: debug
     doorbirdpy: debug
     homeassistant.components.doorbird: debug
```
