### ISSUE TITLE
Entities card show_name and show_icon not working

### ISSUE THREAD

**Issue by AleXSR700** [home-assistant/home-assistant.io#24047]
### Feedback

Hello,

is it possible that show_name and show_icon no longer work?

```
type: entities
entities:
  - entity: sensor.xiaomi_temperature_living_room
    show_name: false
    show_icon: false
```
Results in 
![image](https://user-images.githubusercontent.com/57034871/189153485-084d8d76-a2a6-4960-ae45-88116f368dd0.png)

Whereas name and icon seem to work
```
type: entities
entities:
  - entity: sensor.xiaomi_temperature_living_room
    show_name: false
    show_icon: false
    icon: mdi:ab-testing
    name: test
```
![image](https://user-images.githubusercontent.com/57034871/189153721-60461a98-43b1-45b5-ac98-ae2b56ee1606.png)

### URL

https://www.home-assistant.io/dashboards/entities/

### Version

2022.9.0
