### ISSUE TITLE
Could not reach [test] my.project.id. Please try again.

### ISSUE THREAD

**Issue by Th3S4mur41** [home-assistant/home-assistant.io#38605]
### Feedback

I tried the [manual Google Assistant configuration](https://www.home-assistant.io/integrations/google_assistant#manual-setup-if-you-dont-have-home-assistant-cloud)...

I double- and tripple checked all the requirement, and everything seems to be correct.

My Google Home App version is 3.30.1.6 (Public Preview).
I also configured OAuth for the [Google Assistant SDK](https://www.home-assistant.io/integrations/google_assistant_sdk) which is connected successfully.

Google Assistant is configured to expose a single domain, which only includes one device

```yaml
google_assistant:
  project_id: my-project-id
  service_account: !secret google_assistant_service_account
  report_state: true # Recommended
  expose_by_default: false # Recommended to manually select entities
  exposed_domains:
```

When I try to add my home assistant in Google Home, I am able to find and login (with 2FA) to my home assistant.
The page is then redirected to Google Home which loads for a few seconds and then shows the list of services again with the error: `Could not reach [test] my.project.id. Please try again.`

As part of troubleshooting, I made sure to disable DNS Proxy and Bot Fight Mode for the dedicated cloudflare domain...

Testing the API Endpoint by opening https://[YOUR_HOME_ASSISTANT_URL]/api/google_assistant in a browser, returns "405: Method Not Allowed," indicating the API is reachable from the internet.

The SSL certificate is generated with letsencrypt and is definitely valid.

What am I missing?

### URL

https://www.home-assistant.io/integrations/google_assistant/

### Version

2025.4.2
